import '../styles/tabulation.css';
import logo from '../assets/logoTrans.png';
function Tabulation() {
  return (
    <>
      <div className="header-area">
        <img src={logo} alt="alt" style={{ maxHeight: '60px' }} />
        <h3>ORUESE INTERNATIONAL SCHOOL</h3>
        <h4>Tabulation Sheet</h4>
        <p>
          FIRST TERM Term Boardsheet For (Print Session) Session
          &nbsp;&nbsp;&nbsp;Class JSS 1
        </p>
      </div>
      <div className="table-area">
        <div className="table-responsive-sm">
          <table
            cellPadding="2"
            cellSpacing="2"
            className="table table-bordered"
          >
            <thead>
              <tr>
                <th className="th-one">S/N</th>
                <th className="th-two">Students | Subjects</th>
                <th>
                  <span>MATHEMATICS</span>
                </th>
                <th>
                  <span>ENGLISH LANGUAGE</span>
                </th>
                <th>
                  <span>BASIC SCIENCE</span>
                </th>
                <th>
                  <span>NATIONAL VALUES</span>
                </th>
                <th>
                  <span>BASIC TECHNOLOGY</span>
                </th>
                <th>
                  <span>P.H.E</span>
                </th>
                <th>
                  <span>C.R.S</span>
                </th>
                <th>
                  <span>AGRIC</span>
                </th>
                <th>
                  <span>URHOBO</span>
                </th>
                <th>
                  <span>FRENCH</span>
                </th>
                <th>
                  <span>BUSINESS STUDIES</span>
                </th>
                <th>
                  <span>HOME ECONS</span>
                </th>
                <th>
                  <span>C.C.A</span>
                </th>
                <th>
                  <span>HISTORY</span>
                </th>
                <th>
                  <span>I.C.T</span>
                </th>
                <th>
                  <span>PHONETICS</span>
                </th>
                <th>
                  <span>EXTRA CURRICULAR ACTIVITY</span>
                </th>
                <th>Total</th>
                <th>Average Grade Point</th>
                <th>ClassName Position</th>
                <th>Average Marks</th>
                <th className="th-last">Remarks</th>
              </tr>
            </thead>

            <thead>
              <tr>
                <td>1</td>
                <td style={{ textAlign: 'left' }}>ADEGOR DAVID</td>
                <td style={{ width: '2rem' }}>85</td>
                <td>83</td>
                <td>64</td>
                <td>62</td>
                <td>69</td>
                <td>44</td>
                <td>89</td>
                <td>66</td>
                <td>49</td>
                <td>82</td>
                <td>79</td>
                <td>61</td>
                <td>65</td>
                <td>85</td>
                <td>60</td>
                <td>82</td>
                <td></td>
                <td>1125</td>
                <td>3.88</td>
                <td>13</td>
                <td>66.18</td>

                <td>00</td>
              </tr>
              <tr>
                <td>2</td>
                <td>AKPUDJE VICTORY</td>
                <td>34</td>
                <td>57</td>
                <td>61</td>
                <td>78</td>
                <td>64</td>
                <td>42</td>
                <td>87</td>
                <td>52</td>
                <td>84</td>
                <td>51</td>
                <td>85</td>
                <td>46</td>
                <td>62</td>
                <td>68</td>
                <td>40</td>
                <td>59</td>
                <td></td>
                <td>970</td>
                <td>3.06</td>
                <td>19</td>
                <td>57.06</td>

                <td>00</td>
              </tr>
              <tr>
                <td>3</td>
                <td>ANUKPEYIBO ERICA</td>
                <td>48</td>
                <td>71</td>
                <td>42</td>
                <td>67</td>
                <td>39</td>
                <td>48</td>
                <td>84</td>
                <td>45</td>
                <td>49</td>
                <td>58</td>
                <td>80</td>
                <td>33</td>
                <td>38</td>
                <td>77</td>
                <td>52</td>
                <td>77</td>
                <td></td>
                <td>908</td>
                <td>2.59</td>
                <td>22</td>
                <td>53.41</td>

                <td>00</td>
              </tr>
              <tr>
                <td>4</td>
                <td>ASIN HONEYBELL</td>
                <td>39</td>
                <td>52</td>
                <td>38</td>
                <td>66</td>
                <td>74</td>
                <td>35</td>
                <td>76</td>
                <td>37</td>
                <td>43</td>
                <td>55</td>
                <td>77</td>
                <td>51</td>
                <td>71</td>
                <td>62</td>
                <td>40</td>
                <td>58</td>
                <td></td>
                <td>874</td>
                <td>2.47</td>
                <td>24</td>
                <td>51.41</td>

                <td>00</td>
              </tr>
              <tr>
                <td>5</td>
                <td>ATUBI DEREK</td>
                <td>83</td>
                <td>92</td>
                <td>78</td>
                <td>97</td>
                <td>86</td>
                <td>78</td>
                <td>93</td>
                <td>66</td>
                <td>94</td>
                <td>84</td>
                <td>95</td>
                <td>84</td>
                <td>99</td>
                <td>97</td>
                <td>65</td>
                <td>100</td>
                <td></td>
                <td>1391</td>
                <td>4.59</td>
                <td>1</td>
                <td>81.82</td>

                <td>00</td>
              </tr>
              <tr>
                <td>6</td>
                <td>ATUYOTA BLESSING</td>
                <td>42</td>
                <td>57</td>
                <td>36</td>
                <td>46</td>
                <td>41</td>
                <td>60</td>
                <td>66</td>
                <td>45</td>
                <td>56</td>
                <td>74</td>
                <td>53</td>
                <td>29</td>
                <td>54</td>
                <td>52</td>
                <td>50</td>
                <td>75</td>
                <td></td>
                <td>836</td>
                <td>2.47</td>
                <td>27</td>
                <td>49.18</td>

                <td>00</td>
              </tr>
              <tr>
                <td>7</td>
                <td>ATUYOTA GODSENT</td>
                <td>13</td>
                <td>33</td>
                <td>36</td>
                <td>31</td>
                <td>32</td>
                <td>24</td>
                <td>46</td>
                <td>37</td>
                <td>20</td>
                <td>54</td>
                <td>35</td>
                <td>29</td>
                <td>30</td>
                <td>47</td>
                <td>40</td>
                <td>63</td>
                <td></td>
                <td>570</td>
                <td>0.71</td>
                <td>40</td>
                <td>33.53</td>

                <td>00</td>
              </tr>
              <tr>
                <td>8</td>
                <td>AUTHOR FAVOUR</td>
                <td>71</td>
                <td>78</td>
                <td>67</td>
                <td>81</td>
                <td>65</td>
                <td>44</td>
                <td>95</td>
                <td>48</td>
                <td>91</td>
                <td>91</td>
                <td>80</td>
                <td>63</td>
                <td>60</td>
                <td>73</td>
                <td>54</td>
                <td>87</td>
                <td></td>
                <td>1148</td>
                <td>3.94</td>
                <td>10</td>
                <td>67.53</td>

                <td>00</td>
              </tr>
              <tr>
                <td>9</td>
                <td>EGO AGHOGHO DANIEL</td>
                <td>95</td>
                <td>89</td>
                <td>74</td>
                <td>95</td>
                <td>86</td>
                <td>71</td>
                <td>95</td>
                <td>50</td>
                <td>96</td>
                <td>75</td>
                <td>96</td>
                <td>59</td>
                <td>88</td>
                <td>89</td>
                <td>67</td>
                <td>79</td>
                <td></td>
                <td>1304</td>
                <td>4.41</td>
                <td>3</td>
                <td>76.71</td>

                <td>00</td>
              </tr>
              <tr>
                <td>10</td>
                <td>EJAKPOVI PRECIOUS</td>
                <td>20</td>
                <td>29</td>
                <td>20</td>
                <td>36</td>
                <td>32</td>
                <td>17</td>
                <td>37</td>
                <td>32</td>
                <td>16</td>
                <td>39</td>
                <td>35</td>
                <td>28</td>
                <td>41</td>
                <td>18</td>
                <td>41</td>
                <td>52</td>
                <td></td>
                <td>493</td>
                <td>0.29</td>
                <td>43</td>
                <td>29.00</td>

                <td>00</td>
              </tr>
              <tr>
                <td>11</td>
                <td>EJETA OGHENERUKOME</td>
                <td>93</td>
                <td>76</td>
                <td>84</td>
                <td>85</td>
                <td>94</td>
                <td>79</td>
                <td>98</td>
                <td>53</td>
                <td>74</td>
                <td>68</td>
                <td>87</td>
                <td>78</td>
                <td>58</td>
                <td>84</td>
                <td>62</td>
                <td>77</td>
                <td></td>
                <td>1250</td>
                <td>4.35</td>
                <td>8</td>
                <td>73.53</td>

                <td>00</td>
              </tr>
              <tr>
                <td>12</td>
                <td>EJORIEVWO EMMANUELLA</td>
                <td>56</td>
                <td>71</td>
                <td>0</td>
                <td>54</td>
                <td>43</td>
                <td>29</td>
                <td>80</td>
                <td>47</td>
                <td>74</td>
                <td>58</td>
                <td>63</td>
                <td>46</td>
                <td>71</td>
                <td>69</td>
                <td>56</td>
                <td>54</td>
                <td></td>
                <td>871</td>
                <td>2.82</td>
                <td>25</td>
                <td>51.24</td>

                <td>00</td>
              </tr>
              <tr>
                <td>13</td>
                <td>IFEANYI UKA GODWIN</td>
                <td>31</td>
                <td>57</td>
                <td>29</td>
                <td>78</td>
                <td>37</td>
                <td>30</td>
                <td>69</td>
                <td>46</td>
                <td>32</td>
                <td>64</td>
                <td>61</td>
                <td>34</td>
                <td>38</td>
                <td>65</td>
                <td>40</td>
                <td>58</td>
                <td></td>
                <td>769</td>
                <td>1.76</td>
                <td>30</td>
                <td>45.24</td>

                <td>00</td>
              </tr>
              <tr>
                <td>14</td>
                <td>IGBORI FAVOUR</td>
                <td>42</td>
                <td>47</td>
                <td>28</td>
                <td>49</td>
                <td>29</td>
                <td>26</td>
                <td>76</td>
                <td>31</td>
                <td>37</td>
                <td>56</td>
                <td>54</td>
                <td>38</td>
                <td>68</td>
                <td>58</td>
                <td>41</td>
                <td>57</td>
                <td></td>
                <td>737</td>
                <td>1.59</td>
                <td>34</td>
                <td>43.35</td>

                <td>00</td>
              </tr>
              <tr>
                <td>15</td>
                <td>IGHOYOTA BEST</td>
                <td>70</td>
                <td>84</td>
                <td>42</td>
                <td>54</td>
                <td>66</td>
                <td>44</td>
                <td>88</td>
                <td>50</td>
                <td>64</td>
                <td>44</td>
                <td>84</td>
                <td>43</td>
                <td>70</td>
                <td>71</td>
                <td>42</td>
                <td>80</td>
                <td></td>
                <td>996</td>
                <td>3.18</td>
                <td>16</td>
                <td>58.59</td>

                <td>00</td>
              </tr>
              <tr>
                <td>16</td>
                <td>IKEHIDE ALDRED ELOGHOSA</td>
                <td>89</td>
                <td>91</td>
                <td>73</td>
                <td>88</td>
                <td>75</td>
                <td>62</td>
                <td>98</td>
                <td>61</td>
                <td>75</td>
                <td>83</td>
                <td>98</td>
                <td>56</td>
                <td>87</td>
                <td>96</td>
                <td>70</td>
                <td>91</td>
                <td></td>
                <td>1293</td>
                <td>4.47</td>
                <td>4</td>
                <td>76.06</td>

                <td>00</td>
              </tr>
              <tr>
                <td>17</td>
                <td>IMENE ZION OGHENERUNOR</td>
                <td>81</td>
                <td>84</td>
                <td>66</td>
                <td>88</td>
                <td>77</td>
                <td>71</td>
                <td>93</td>
                <td>51</td>
                <td>100</td>
                <td>83</td>
                <td>97</td>
                <td>71</td>
                <td>89</td>
                <td>76</td>
                <td>49</td>
                <td>85</td>
                <td></td>
                <td>1261</td>
                <td>4.35</td>
                <td>7</td>
                <td>74.18</td>

                <td>00</td>
              </tr>
              <tr>
                <td>18</td>
                <td>ITOYA BELIEVE AYEMERE</td>
                <td>52</td>
                <td>64</td>
                <td>34</td>
                <td>54</td>
                <td>45</td>
                <td>23</td>
                <td>46</td>
                <td>36</td>
                <td>33</td>
                <td>57</td>
                <td>44</td>
                <td>41</td>
                <td>45</td>
                <td>41</td>
                <td>41</td>
                <td>50</td>
                <td></td>
                <td>706</td>
                <td>1.53</td>
                <td>36</td>
                <td>41.53</td>

                <td>00</td>
              </tr>
              <tr>
                <td>19</td>
                <td>JOSHUA GRACE</td>
                <td>78</td>
                <td>87</td>
                <td>51</td>
                <td>60</td>
                <td>57</td>
                <td>24</td>
                <td>81</td>
                <td>51</td>
                <td>74</td>
                <td>73</td>
                <td>75</td>
                <td>55</td>
                <td>67</td>
                <td>72</td>
                <td>58</td>
                <td>88</td>
                <td></td>
                <td>1051</td>
                <td>3.71</td>
                <td>15</td>
                <td>61.82</td>

                <td>00</td>
              </tr>
              <tr>
                <td>20</td>
                <td>LEKEE ERNEST OGHENEFEGA</td>
                <td>59</td>
                <td>56</td>
                <td>40</td>
                <td>60</td>
                <td>44</td>
                <td>41</td>
                <td>89</td>
                <td>33</td>
                <td>43</td>
                <td>58</td>
                <td>42</td>
                <td>36</td>
                <td>46</td>
                <td>62</td>
                <td>54</td>
                <td>52</td>
                <td></td>
                <td>815</td>
                <td>2.06</td>
                <td>28</td>
                <td>47.94</td>

                <td>00</td>
              </tr>
              <tr>
                <td>21</td>
                <td>LONDON JUBILEE</td>
                <td>70</td>
                <td>63</td>
                <td>49</td>
                <td>63</td>
                <td>66</td>
                <td>34</td>
                <td>77</td>
                <td>42</td>
                <td>69</td>
                <td>57</td>
                <td>72</td>
                <td>32</td>
                <td>78</td>
                <td>62</td>
                <td>47</td>
                <td>87</td>
                <td></td>
                <td>968</td>
                <td>3.12</td>
                <td>20</td>
                <td>56.94</td>

                <td>00</td>
              </tr>
              <tr>
                <td>22</td>
                <td>MALIKI EMMANUEL</td>
                <td>62</td>
                <td>42</td>
                <td>44</td>
                <td>57</td>
                <td>62</td>
                <td>45</td>
                <td>74</td>
                <td>41</td>
                <td>22</td>
                <td>55</td>
                <td>68</td>
                <td>65</td>
                <td>79</td>
                <td>61</td>
                <td>49</td>
                <td>64</td>
                <td></td>
                <td>890</td>
                <td>2.76</td>
                <td>23</td>
                <td>52.35</td>

                <td>00</td>
              </tr>
              <tr>
                <td>23</td>
                <td>OBINYAN EXCELLENT</td>
                <td>64</td>
                <td>70</td>
                <td>59</td>
                <td>76</td>
                <td>78</td>
                <td>50</td>
                <td>95</td>
                <td>47</td>
                <td>51</td>
                <td>70</td>
                <td>90</td>
                <td>61</td>
                <td>70</td>
                <td>73</td>
                <td>47</td>
                <td>71</td>
                <td></td>
                <td>1072</td>
                <td>3.88</td>
                <td>14</td>
                <td>63.06</td>

                <td>00</td>
              </tr>
              <tr>
                <td>24</td>
                <td>OGBARO JOSHUA</td>
                <td>42</td>
                <td>52</td>
                <td>48</td>
                <td>48</td>
                <td>44</td>
                <td>27</td>
                <td>69</td>
                <td>50</td>
                <td>49</td>
                <td>51</td>
                <td>57</td>
                <td>48</td>
                <td>60</td>
                <td>42</td>
                <td>45</td>
                <td>65</td>
                <td></td>
                <td>797</td>
                <td>2.18</td>
                <td>29</td>
                <td>46.88</td>

                <td>00</td>
              </tr>
              <tr>
                <td>25</td>
                <td>OKEFE MIRACLE</td>
                <td>31</td>
                <td>57</td>
                <td>40</td>
                <td>26</td>
                <td>22</td>
                <td>25</td>
                <td>58</td>
                <td>36</td>
                <td>44</td>
                <td>71</td>
                <td>42</td>
                <td>29</td>
                <td>50</td>
                <td>34</td>
                <td>42</td>
                <td>58</td>
                <td></td>
                <td>665</td>
                <td>1.24</td>
                <td>39</td>
                <td>39.12</td>

                <td>00</td>
              </tr>
              <tr>
                <td>26</td>
                <td>OKOTIE MULTIPLIER</td>
                <td>70</td>
                <td>40</td>
                <td>12</td>
                <td>40</td>
                <td>42</td>
                <td>14</td>
                <td>51</td>
                <td>36</td>
                <td>38</td>
                <td>51</td>
                <td>59</td>
                <td>26</td>
                <td>40</td>
                <td>34</td>
                <td>55</td>
                <td>59</td>
                <td></td>
                <td>667</td>
                <td>1.41</td>
                <td>38</td>
                <td>39.24</td>

                <td>00</td>
              </tr>
              <tr>
                <td>27</td>
                <td>OKOYE CARANA</td>
                <td>79</td>
                <td>74</td>
                <td>69</td>
                <td>96</td>
                <td>90</td>
                <td>70</td>
                <td>95</td>
                <td>60</td>
                <td>74</td>
                <td>72</td>
                <td>91</td>
                <td>78</td>
                <td>81</td>
                <td>95</td>
                <td>62</td>
                <td>89</td>
                <td></td>
                <td>1275</td>
                <td>4.53</td>
                <td>6</td>
                <td>75.00</td>

                <td>00</td>
              </tr>
              <tr>
                <td>28</td>
                <td>OKUMOLUWA DEBORAH</td>
                <td>69</td>
                <td>61</td>
                <td>53</td>
                <td>54</td>
                <td>60</td>
                <td>43</td>
                <td>73</td>
                <td>48</td>
                <td>68</td>
                <td>90</td>
                <td>70</td>
                <td>35</td>
                <td>78</td>
                <td>69</td>
                <td>41</td>
                <td>67</td>
                <td></td>
                <td>979</td>
                <td>3.18</td>
                <td>17</td>
                <td>57.59</td>

                <td>00</td>
              </tr>
              <tr>
                <td>29</td>
                <td>OKWUDIRE JOY NGOZICHUKWU</td>
                <td>81</td>
                <td>80</td>
                <td>78</td>
                <td>92</td>
                <td>76</td>
                <td>67</td>
                <td>96</td>
                <td>54</td>
                <td>82</td>
                <td>81</td>
                <td>96</td>
                <td>78</td>
                <td>97</td>
                <td>92</td>
                <td>65</td>
                <td>90</td>
                <td></td>
                <td>1305</td>
                <td>4.47</td>
                <td>2</td>
                <td>76.76</td>

                <td>00</td>
              </tr>
              <tr>
                <td>30</td>
                <td>ONAGINOR MARVELOUS</td>
                <td>44</td>
                <td>59</td>
                <td>28</td>
                <td>41</td>
                <td>41</td>
                <td>30</td>
                <td>71</td>
                <td>48</td>
                <td>50</td>
                <td>48</td>
                <td>52</td>
                <td>49</td>
                <td>36</td>
                <td>33</td>
                <td>49</td>
                <td>54</td>
                <td></td>
                <td>733</td>
                <td>1.65</td>
                <td>35</td>
                <td>43.12</td>

                <td>00</td>
              </tr>
              <tr>
                <td>31</td>
                <td>ONORIODE PRAISE OGHENEFEGOR</td>
                <td>32</td>
                <td>50</td>
                <td>41</td>
                <td>36</td>
                <td>44</td>
                <td>21</td>
                <td>60</td>
                <td>45</td>
                <td>56</td>
                <td>57</td>
                <td>34</td>
                <td>39</td>
                <td>35</td>
                <td>25</td>
                <td>45</td>
                <td>54</td>
                <td></td>
                <td>674</td>
                <td>1.29</td>
                <td>37</td>
                <td>39.65</td>

                <td>00</td>
              </tr>
              <tr>
                <td>32</td>
                <td>ORISAMOLUWA AYO SONIA</td>
                <td>15</td>
                <td>12</td>
                <td>4</td>
                <td>5</td>
                <td>6</td>
                <td>5</td>
                <td>19</td>
                <td>0</td>
                <td>57</td>
                <td>17</td>
                <td>5</td>
                <td>9</td>
                <td>20</td>
                <td>11</td>
                <td>11</td>
                <td>16</td>
                <td></td>
                <td>212</td>
                <td>0.18</td>
                <td>45</td>
                <td>12.47</td>

                <td>00</td>
              </tr>
              <tr>
                <td>33</td>
                <td>OSANEBI ALICIA UFUOMA</td>
                <td>69</td>
                <td>76</td>
                <td>42</td>
                <td>59</td>
                <td>51</td>
                <td>32</td>
                <td>69</td>
                <td>45</td>
                <td>60</td>
                <td>55</td>
                <td>62</td>
                <td>51</td>
                <td>64</td>
                <td>68</td>
                <td>40</td>
                <td>68</td>
                <td></td>
                <td>911</td>
                <td>2.88</td>
                <td>21</td>
                <td>53.59</td>

                <td>00</td>
              </tr>
              <tr>
                <td>34</td>
                <td>PEREWARE BRAKE-EMI</td>
                <td>91</td>
                <td>83</td>
                <td>63</td>
                <td>82</td>
                <td>55</td>
                <td>38</td>
                <td>92</td>
                <td>49</td>
                <td>72</td>
                <td>68</td>
                <td>91</td>
                <td>58</td>
                <td>81</td>
                <td>79</td>
                <td>48</td>
                <td>81</td>
                <td></td>
                <td>1131</td>
                <td>3.71</td>
                <td>12</td>
                <td>66.53</td>

                <td>00</td>
              </tr>
              <tr>
                <td>35</td>
                <td>ROBERT SHARON LADI</td>
                <td>85</td>
                <td>82</td>
                <td>82</td>
                <td>92</td>
                <td>83</td>
                <td>60</td>
                <td>98</td>
                <td>45</td>
                <td>69</td>
                <td>80</td>
                <td>93</td>
                <td>74</td>
                <td>93</td>
                <td>94</td>
                <td>53</td>
                <td>95</td>
                <td></td>
                <td>1278</td>
                <td>4.29</td>
                <td>5</td>
                <td>75.18</td>

                <td>00</td>
              </tr>
              <tr>
                <td>36</td>
                <td>RUSSIA GREAT</td>
                <td>32</td>
                <td>57</td>
                <td>32</td>
                <td>59</td>
                <td>41</td>
                <td>33</td>
                <td>82</td>
                <td>40</td>
                <td>57</td>
                <td>43</td>
                <td>56</td>
                <td>41</td>
                <td>55</td>
                <td>49</td>
                <td>40</td>
                <td>47</td>
                <td></td>
                <td>764</td>
                <td>1.71</td>
                <td>31</td>
                <td>44.94</td>

                <td>00</td>
              </tr>
              <tr>
                <td>37</td>
                <td>SERO GOODLUCK</td>
                <td>58</td>
                <td>67</td>
                <td>57</td>
                <td>65</td>
                <td>66</td>
                <td>43</td>
                <td>79</td>
                <td>55</td>
                <td>52</td>
                <td>69</td>
                <td>67</td>
                <td>61</td>
                <td>59</td>
                <td>77</td>
                <td>40</td>
                <td>62</td>
                <td></td>
                <td>977</td>
                <td>3.24</td>
                <td>18</td>
                <td>57.47</td>

                <td>00</td>
              </tr>
              <tr>
                <td>38</td>
                <td>SUNDAY LISA</td>
                <td>32</td>
                <td>49</td>
                <td>18</td>
                <td>51</td>
                <td>44</td>
                <td>29</td>
                <td>77</td>
                <td>45</td>
                <td>40</td>
                <td>53</td>
                <td>71</td>
                <td>35</td>
                <td>52</td>
                <td>64</td>
                <td>40</td>
                <td>57</td>
                <td></td>
                <td>757</td>
                <td>1.94</td>
                <td>32</td>
                <td>44.53</td>

                <td>00</td>
              </tr>
              <tr>
                <td>39</td>
                <td>TUOYO JAMES OMAGHOMI</td>
                <td>80</td>
                <td>88</td>
                <td>74</td>
                <td>78</td>
                <td>72</td>
                <td>67</td>
                <td>98</td>
                <td>49</td>
                <td>65</td>
                <td>55</td>
                <td>96</td>
                <td>76</td>
                <td>70</td>
                <td>82</td>
                <td>56</td>
                <td>84</td>
                <td></td>
                <td>1190</td>
                <td>4.18</td>
                <td>9</td>
                <td>70.00</td>

                <td>00</td>
              </tr>
              <tr>
                <td>40</td>
                <td>UKOKO DANIELLA</td>
                <td>42</td>
                <td>53</td>
                <td>42</td>
                <td>44</td>
                <td>45</td>
                <td>48</td>
                <td>77</td>
                <td>40</td>
                <td>51</td>
                <td>70</td>
                <td>52</td>
                <td>54</td>
                <td>55</td>
                <td>55</td>
                <td>53</td>
                <td>57</td>
                <td></td>
                <td>838</td>
                <td>2.47</td>
                <td>26</td>
                <td>49.29</td>

                <td>00</td>
              </tr>
              <tr>
                <td>41</td>
                <td>OKORO LAURA</td>
                <td>32</td>
                <td>45</td>
                <td>38</td>
                <td>38</td>
                <td>45</td>
                <td>33</td>
                <td>83</td>
                <td>53</td>
                <td>37</td>
                <td>65</td>
                <td>61</td>
                <td>44</td>
                <td>50</td>
                <td>47</td>
                <td>40</td>
                <td>42</td>
                <td></td>
                <td>753</td>
                <td>1.65</td>
                <td>33</td>
                <td>44.29</td>

                <td>00</td>
              </tr>
              <tr>
                <td>42</td>
                <td>OYOVWE MIRACLE</td>
                <td>60</td>
                <td>67</td>
                <td>61</td>
                <td>72</td>
                <td>74</td>
                <td>65</td>
                <td>88</td>
                <td>59</td>
                <td>95</td>
                <td>66</td>
                <td>86</td>
                <td>67</td>
                <td>81</td>
                <td>75</td>
                <td>48</td>
                <td>71</td>
                <td></td>
                <td>1135</td>
                <td>4.06</td>
                <td>11</td>
                <td>66.76</td>

                <td>00</td>
              </tr>
              <tr>
                <td>43</td>
                <td>OVIE FEJIRO</td>
                <td>51</td>
                <td>45</td>
                <td>34</td>
                <td>25</td>
                <td>26</td>
                <td>20</td>
                <td>44</td>
                <td>35</td>
                <td>14</td>
                <td>58</td>
                <td>44</td>
                <td>8</td>
                <td>36</td>
                <td>14</td>
                <td>40</td>
                <td>46</td>
                <td></td>
                <td>540</td>
                <td>0.76</td>
                <td>41</td>
                <td>31.76</td>

                <td>00</td>
              </tr>
              <tr>
                <td>44</td>
                <td>ATORI PRECIOUS</td>
                <td>15</td>
                <td>52</td>
                <td>25</td>
                <td>28</td>
                <td>32</td>
                <td>16</td>
                <td>28</td>
                <td>25</td>
                <td>18</td>
                <td>34</td>
                <td>26</td>
                <td>25</td>
                <td>40</td>
                <td>28</td>
                <td>40</td>
                <td>63</td>
                <td></td>
                <td>495</td>
                <td>0.53</td>
                <td>42</td>
                <td>29.12</td>

                <td>00</td>
              </tr>
              <tr>
                <td>45</td>
                <td>IGBESOKO DIVINE</td>
                <td>15</td>
                <td>35</td>
                <td>10</td>
                <td>24</td>
                <td>18</td>
                <td>17</td>
                <td>58</td>
                <td>33</td>
                <td>40</td>
                <td>41</td>
                <td>26</td>
                <td>23</td>
                <td>35</td>
                <td>25</td>
                <td>25</td>
                <td>44</td>
                <td></td>
                <td>469</td>
                <td>0.35</td>
                <td>44</td>
                <td>27.59</td>

                <td>00</td>
              </tr>
              <tr>
                <td>46</td>
                <td>OKOKO OGHENEVWEGBA</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>0</td>
                <td>0.00</td>
                <td>46</td>
                <td>0.00</td>

                <td>00</td>
              </tr>
              <tr>
                <td>47</td>
                <td>SHOLA OMOMOWO</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>0</td>
                <td>0.00</td>
                <td>46</td>
                <td>0.00</td>

                <td>00</td>
              </tr>
            </thead>
          </table>
          <table
            cellPadding="2"
            cellSpacing="2"
            className="table table-bordered"
          >
            <tbody>
              <tr>
                <td>Number of students</td>
                <td>47</td>
                <td>Number Of Passed</td>
                <td>45</td>
                <td>Number of Failed</td>
                <td>2</td>
                <td>Name of Form Teacher</td>
                <td>VIVIAN EFEMIEMIE</td>
              </tr>
            </tbody>
          </table>
          &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          <table>
            <tbody>
              <tr>
                <td>Signature/Date</td>
                <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
                <td>School Stamp</td>
              </tr>

              <tr>
                <td>....................</td>
                <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
                <td>....................</td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </>
  );
}

export default Tabulation;
